/*
 * @file: Images.js
 * @description: Images constants file for the application
 * @date: 15.12.2016
 * @author: Manish Budhiraja
 * */

'use strict';
module.exports = {
	backgrounds:{
		background_consumer		: require("../assets/images/background.png"),
		background_chef_caterer : require("../assets/images/background1.png"),
	},
	user:{
		caterer 				: require("../assets/images/caterer.png"),
		chef					: require("../assets/images/chef.png"),
		customer				: require("../assets/images/customer.png"),
		anyday_filter    		: require("../assets/images/anyday_filter.png"),
		anytime_filter   		: require("../assets/images/anytime_filter.png"),
		anywhere_filter    		: require("../assets/images/anywhere_filter.png"),
		bottom_bookings_active  : require("../assets/images/bottom_bookings_active.png"),
		bottom_bookings    		: require("../assets/images/bottom_bookings.png"),
		bottom_explore_active   : require("../assets/images/bottom_explore_active.png"),
		bottom_explore    		: require("../assets/images/bottom_explore.png"),
		bottom_messages_active  : require("../assets/images/bottom_messages_active.png"),
		bottom_messages  		: require("../assets/images/bottom_messages.png"),
		bottom_payments_active	: require("../assets/images/bottom_payments_active.png"),
		bottom_payments 		: require("../assets/images/bottom_payments.png"),
		bottom_profile_active	: require("../assets/images/bottom_profile_active.png"),
		bottom_profile 			: require("../assets/images/bottom_profile.png"),
		caterer_star			: require("../assets/images/caterer_star.png"),
		catering_filter 		: require("../assets/images/catering_filter.png"),
		menu_arrow 				: require("../assets/images/menu_arrow.png"),
		input_checkbox 			: require("../assets/images/input_checkbox.png"),
		loc						: require("../assets/images/loc.png"),
		play_icon 				: require("../assets/images/play_icon.png"),
	    payment_bg_back 		: require("../assets/images/payment_back.png"),
		payment_bg_white 		: require("../assets/images/payment_white.png"),
   		payment_bg 				: require("../assets/images/payments_bg.png"),
   		noti_icon				: require("../assets/images/noti_icon.png"),
   		searchIcon				: require("../assets/images/searchIcon.png"),
   		next					: require("../assets/images/next.png"),
   		prev 					: require("../assets/images/prev.png"),
	},
	caterer:{
		about_arrow    			: require("../assets/images/about_arrow.png"),
		add_details_arrow    	: require("../assets/images/add_details_arrow.png"),
		add_image    			: require("../assets/images/add_image.png"),
		add_work_image    		: require("../assets/images/add_work_image.png"),
		appointment    			: require("../assets/images/appointment.png"),
		arrow_down    			: require("../assets/images/arrow_down.png"),
		arrow_green    			: require("../assets/images/arrow_green.png"),
		arrow_right    			: require("../assets/images/arrow_right.png"),
		arrow_signup    		: require("../assets/images/arrow_signup.png"),
		availability    		: require("../assets/images/availability.png"),
		back    				: require("../assets/images/back.png"),
		booking_ended_dispute   : require("../assets/images/booking_ended_dispute.png"),
		booking_ended_star_gray : require("../assets/images/booking_ended_star_gray.png"),
		booking_ended_star_green: require("../assets/images/booking_ended_star_green.png"),
		call_gray    			: require("../assets/images/call_gray.png"),
		checkbox_selected    	: require("../assets/images/checkbox_selected.png"),
		checkbox    			: require("../assets/images/checkbox.png"),
		close    				: require("../assets/images/close.png"),
		dispute    				: require("../assets/images/dispute.png"),
		gray_toggle_signup    	: require("../assets/images/gray_toggle_signup.png"),
		green_toggle_signup    	: require("../assets/images/green_toggle_signup.png"),
		message_gray    		: require("../assets/images/message_gray.png"),
		messages    			: require("../assets/images/messages.png"),
		password_hide    		: require("../assets/images/password_hide.png"),
		payments    			: require("../assets/images/payments.png"),
		paymentsbg    			: require("../assets/images/payments_bg.png"),
		profile_toggle_gray    	: require("../assets/images/profile_toggle_gray.png"),
		profile_toggle_green    : require("../assets/images/profile_toggle_green.png"),
		profile    				: require("../assets/images/profile.png"),
		request    				: require("../assets/images/request.png"),
		star_gray_rateuser    	: require("../assets/images/star_gray_rateuser.png"),
		star_gray    			: require("../assets/images/star_gray.png"),
		star_green_rateuser    	: require("../assets/images/star_green_rateuser.png"),
		star_green    			: require("../assets/images/star_green.png"),
		toggle_gray    			: require("../assets/images/toggle_gray.png"),
		toggle_green    		: require("../assets/images/toggle_green.png"),
		right_arrow             : require("../assets/images/right_arrow.png"),
		reports             	: require("../assets/images/report.png"),
		dummyimage             	: require("../assets/images/dummyimage.jpg"),
	}
};
